# Generated by Django 3.2.15 on 2022-09-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('keyword', models.CharField(max_length=150, verbose_name='keyword')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='childern')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug')),
                ('in_stock', models.BooleanField(default=True, verbose_name='in_stock')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='date add')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('selling_price', models.FloatField(default=0, verbose_name='selling price')),
                ('discount_price', models.FloatField(default=0, verbose_name='discount price')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('warranty', models.CharField(blank=True, max_length=250, null=True, verbose_name='warranty')),
                ('policy', models.CharField(blank=True, max_length=250, null=True, verbose_name='policy')),
                ('keyword', models.CharField(max_length=150, verbose_name='keyword')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('main_pic', models.ImageField(upload_to='product', verbose_name='main image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product', verbose_name='main image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
